server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/Arturo/Repositories/Github/Git-A/BuildingMicroservicesWithSpringCloud/confserv/src/main/resources/config/licensingservice,
                           file:///Users/Arturo/Repositories/Github/Git-A/BuildingMicroservicesWithSpringCloud/confserv/src/main/resources/config/organizationservice
        encrypt:
          enabled: false