version: '3'
services:
  configserver:
    image: arturodl/bms-configserver:develop
    container_name: configserver
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"       
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"
  eurekaserver:   
   image:   arturodl/bms-eurekaserver:develop
   container_name: eurekaserver
   ports:
       - "8761:8761"  
  licensingservice:    
   image: arturodl/bms-licensingservice:develop
   container_name: licensingservice
   ports:
      - "8090:8090"
   links:
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "kafkaserver:kafkaserver"
      - "redis:redis"
      - "database:database"
   environment:
      PROFILE: "default"
      SERVER_PORT: "8090"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC" 
  organizationservice:
    image: arturodl/bms-organizationservice:develop
    container_name: organizationservice
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC" 
  zuulserver:
    image: arturodl/bms-zuulserver:develop
    container_name: zuulserver
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC" 
  authenticationservice:
    image: arturodl/bms-authenticationservice:develop
    container_name: authenticationservice
    ports: 
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC" 
  database:
    image: postgres:9.5
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=eagle_eye_local 
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379    
  kafkaserver:    
    image: spotify/kafka
    container_name: kafkaserver
    ports:
      - 2181:2181
      - 9092:9092 

#networks:
#  default:
#    external:
#      name: microservices