server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/Arturo/Proyects/Eclipse/Oxygen/SpacePrincipal/Maven/confserv/src/main/resources/config/licensingservice

  