server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/, classpath:config/licensingservice, classpath:config/organizationservice, classpath:config/authenticationservice
          #searchLocations: file:///Users/Arturo/Repositories/Git/Github/arturodl/BuildingMicroservicesWithSpringCloud/confserv/src/main/resources/config/licensingservice,
          #                  file:///Users/Arturo/Repositories/Git/Github/arturodl/BuildingMicroservicesWithSpringCloud/confserv/src/main/resources/config/organizationservice,
          #                  file:///Users/Arturo/Repositories/Git/Github/arturodl/BuildingMicroservicesWithSpringCloud/confserv/src/main/resources/config/authenticationservice
        encrypt:
          enabled: false