spring:
  application:
    name: organizationservice
  profiles:
    active:
      default
  cloud:
   config:
     uri: http://localhost:8888
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#security:
#  oauth2:
#   resource:
#     userInfoUri: http://localhost:8901/auth/user